# Dataset Generators

In [4]:
import pandas as pd
from sklearn.datasets import (
    make_classification,
    make_multilabel_classification,
    make_moons,
    make_biclusters,
    make_sparse_uncorrelated,
)

import matplotlib.pyplot as plt

Generate custom samples

https://scikit-learn.org/stable/datasets/sample_generators.html

Make a custom classification dataset

https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html#sklearn.datasets.make_classification

In [13]:
X, y = make_classification(
    n_classes=2,
    n_samples=100,
    n_features=20,
    # n_informative=10,
    # n_redundant=5,
    # n_clusters_per_class=2,
    random_state=0,  # reproducibility
)

df = pd.DataFrame(X, columns=[f"feature_{i}" for i in range(X.shape[1])])
df["target"] = y
df.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,target
0,-0.039268,0.131912,-0.211206,-1.214147,1.050045,-0.421328,0.768771,0.875696,2.451230,-0.480242,...,-0.523251,0.708695,-1.980566,-1.365163,-0.948933,1.947099,1.976989,1.021225,-0.469311,0
1,0.774161,0.104907,-0.332812,-1.270350,0.379113,-0.822828,-0.612626,1.496140,0.568459,-0.467493,...,-0.862493,-0.631192,0.133913,-0.972403,-0.774459,1.346221,1.267804,0.622519,-1.490265,0
2,-0.014858,0.670570,-0.214167,0.250202,0.055489,-1.566995,0.039767,0.265688,1.849591,0.719984,...,-1.102906,0.019279,-0.707506,0.723100,0.821406,0.024612,-0.104862,-0.101697,-0.451303,1
3,0.038909,-1.557999,-0.024549,0.216543,0.065274,-0.675594,0.844996,2.042072,-1.102230,-1.692370,...,0.729346,-0.298760,-0.507035,0.038118,0.626564,-0.578918,-0.071560,0.699136,-0.993361,1
4,0.936446,1.265078,-0.510293,-0.683049,-1.127849,0.679975,-0.704921,-0.290397,-0.386871,-0.803141,...,-0.464338,-0.552541,0.211497,1.327783,-0.035095,-0.101281,-0.800221,1.021791,-0.696327,1

In [ ]:
X, y = make_multilabel_classification(n_labels=3, random_state=42)
X.shape
y.shape
list(y[:3])